apiVersion: v1
kind: Secret
metadata:
  name: credential-secret
type: Opaque
stringData:
  credentials: |-
    [default]
    region=ap-south-1
    aws_access_key_id=xxxxxxx
    aws_secret_access_key=xxxxxxxxxxx
  config: |-
    [default]
    region=ap-south-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli-deployment
  labels:
    app: awscli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
      - image: nerdlaunda/awscli:latest
        name: awscli-container
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 5;done"]
        volumeMounts:
        - name: aws-credential
          mountPath: "/root/.aws"
          readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"  
      volumes:
      - name: aws-credential
        secret:
          secretName: credential-secret
          optional: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always